sudo: required

services:
  - docker

script:
  - npm run test

after_success:
  - echo branch;
  - if [$TRAVIS_BRANCH == "master" ]; then
      echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin;
      docker build -t rhernandog/dockerhub-travis-test .;
      docker push rhernandog/dockerhub-travis-test;
    fi
